### PR TITLE
feat: spec 3.16

### PR DESCRIPTION
**Pull request by zobo**
Hi @muglug !
This is a combined effort between @tm1000 and me. I currently maintain https://github.com/zobo/vscode-php-intellisense and https://github.com/zobo/php-language-server forks of Felixes original projects (as well as https://github.com/xdebug/vscode-php-debug).
I initially extended the LSP definitions to support Work Done Progress messages - adding support to PHP LS indexing - but then merged together all 3.16 classes defined by Andrew. I also migrated to GH Actions.

The PR is not ready to be merged, I just wanted to check if you'd consider merging it, when I get it to proper quality.

### CODE REVIEW

**Comment by muglug** [comment]
Absolutely will consider merging it!

**Comment by tm1000** [comment]
Thanks @zobo and @muglug !

**Comment by zobo** [comment]
Great!
As said the PR includes the following:
- Change branch to main
- Migrate from travis-ci.org to GH Actions
- Class updates for LSP 3.16

The first point is completely optional, I did it just because Felix has done that on some other repos. If it causes any inconvenience, I'd revert that part.

The GH Actions migration I would strongly suggest. If you agree with that, I'll take prepare also the release part of the workflow.

Let ne know how you'd like to proceed.

**Comment by tm1000** [comment]
ping @muglug

**Comment by muglug** [comment]
Sorry, now merged!

**Comment by zobo** [comment]
Great thanks. But if you intend to leave "master" as the main branch - witch I actually support in this case, there's a small fix that needs to be merged. I'll make another PR to correct this.

**Pull request merged**
