### PR TITLE
fix: PHP 8.4 implicit nullable deprecations

### PR DESCRIPTION
**Pull request by GromNaN**
Implicitly nullable parameters are deprecated in PHP 8.4.

This PR makes the nullable type explicit: https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated

### CODE REVIEW

**Review by muglug — APPROVED** [review]

**Comment by muglug** [comment]
Thanks!

**Comment by GromNaN** [comment]
Hello @muglug, could you release a bugfix version please. Thank you.

**Comment by hafezdivandari** [comment]
Hi @muglug, would you please release this one? many packages / PRs depend on this, thanks.

Thank you @GromNaN

**Comment by muglug** [comment]
Done! Sorry for the delay

**Pull request merged**
